springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /docs
    disable-swagger-default-url: true

jwt:
  secret: 591DF9176D24FABE8E9CB1B37334EA591DF9176D24FABE8E9CB1B37334EA
  access-token-expiration: 180000
  refresh-token-expiration: 600000