spring:
  application:
    name: scrap-chef
  datasource:
    url: jdbc:mariadb://localhost:3306/scrap_chef # 데이터베이스 URL
    username: root                                # 데이터베이스 사용자 이름
    password: root                                # 데이터베이스 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  springdoc:
    api-docs:
      path: /api-docs
      enabled: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      operations-sorter: alpha
      tags-sorter: alpha
      path: /docs
      disable-swagger-default-url: true
