springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /docs
    disable-swagger-default-url: true
